### ISSUE TITLE
Can not run in the IOS platform

### ISSUE THREAD

**Issue by rhymelph** [Particle-Network/particle-flutter#11]
<img width="888" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/20870368/3a90333d-f33d-4cc6-a10b-4101f88e1f31">

**Comment by SunZhiC** [comment]
1. these DownloadProxyFramework is not our SDKs or submodules.
2. the flutter package particle-auth-core doesn't support any iOS simulators, you should run with a real iPhone.

**Comment by rhymelph** [comment]
Yes , i use the real iPhone, but can not running.

**Comment by SunZhiC** [comment]
> Yes , i use the real iPhone, but can not running.

Can you compare your Podfile with https://github.com/Particle-Network/particle-flutter/blob/master/particle-auth-core/example/ios/Podfile?
Did you add 
```
installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
```
Did you specify the pod version?

**Comment by rhymelph** [comment]
My Podfile:
```
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    xcconfig_path = config.base_configuration_reference.real_path
    xcconfig = File.read(xcconfig_path)
    xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
    File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
```

**Comment by SunZhiC** [comment]
> My Podfile:
> 
> ```
> # Uncomment this line to define a global platform for your project
> platform :ios, '14.0'
> # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> 
> project 'Runner', {
>   'Debug' => :debug,
>   'Profile' => :release,
>   'Release' => :release,
> }
> 
> def flutter_root
>   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
>   unless File.exist?(generated_xcode_build_settings_path)
>     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
>   end
> 
>   File.foreach(generated_xcode_build_settings_path) do |line|
>     matches = line.match(/FLUTTER_ROOT\=(.*)/)
>     return matches[1].strip if matches
>   end
>   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
> end
> 
> require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
> 
> flutter_ios_podfile_setup
> 
> target 'Runner' do
>   use_frameworks! :linkage => :static
>   use_modular_headers!
> 
>   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>     config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
>     xcconfig_path = config.base_configuration_reference.real_path
>     xcconfig = File.read(xcconfig_path)
>     xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
>     File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
>     end
>   end
> end
> ```

I see, you should specify the iOS native SDK version in Podfile, with the latest flutter package version number 1.4.4.
if you are using particle_auth_core package. copy 
```
target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  pod "Thresh", '1.3.4'
  pod "ParticleMPCCore", '1.3.4'
  pod "ParticleAuthCore", '1.3.4'
  pod "AuthCoreAdapter", '1.3.4'

  pod 'ParticleAuthService', '1.3.9'
  pod 'ParticleNetworkBase', '1.3.9'
  pod 'ConnectCommon', '0.2.15'
    
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
```
into your Podfile

**Comment by rhymelph** [comment]
Thanks for your reply, I just tried it and still have the same problem.😰

**Comment by SunZhiC** [comment]
> @SunZhiC Thanks for your reply, I just tried it and still have the same problem.😰

After changed your Podflie, you should clean your xcode cache, `command+shift+K` , remove Podfile.lock and Pods folder, 
run `pod install --repo-update` 

Can you try to run our example?

**Comment by rhymelph** [comment]
@SunZhiC I tried it and still have the same problem.
1. clean the xcode cache
2. 
```
flutter clean
flutter packages get
```
3. pod install --repo-update
4. flutter run

**Comment by SunZhiC** [comment]
> @SunZhiC I tried it and still have the same problem.
> 
> 1. clean the xcode cache
> 
> ```
> flutter clean
> flutter packages get
> ```
> 
> 3. pod install --repo-update
> 4. flutter run
> 
> <img alt="image" width="1134" src="https://private-user-images.githubusercontent.com/20870368/297705640-2e2cc9b0-17f5-423b-b9a5-d81227f18f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzQ1MjAsIm5iZiI6MTcwNTU3NDIyMCwicGF0aCI6Ii8yMDg3MDM2OC8yOTc3MDU2NDAtMmUyY2M5YjAtMTdmNS00MjNiLWI5YTUtZDgxMjI3ZjE4ZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEwMzcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMTJkMTJkMGRkMTQzYWIwYTVjOTE4YmUzYzhmMjZlMmJjNWIxYjcxNjRlYzIzOTFkNDk0ODJmNTQwZTE4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BX-4BZbvO-T7w7jeEzQW6cd0SBSWDPD-bDtvshLoTa8">

I suppose the error comes from the mismatch between flutter package version and iOS pod version, can you check your Podfile.lock, whether there SDKs version is right.
```
pod "Thresh", '1.3.4'
pod "ParticleMPCCore", '1.3.4'
pod "ParticleAuthCore", '1.3.4'
pod "AuthCoreAdapter", '1.3.4'

pod 'ParticleAuthService', '1.3.9'
pod 'ParticleNetworkBase', '1.3.9'
pod 'ConnectCommon', '0.2.15'
```

**Comment by SunZhiC** [comment]
Also, can you download our example, which is completely integrated, it should be run successfully, then compare it with your project.

**Comment by SunZhiC** [comment]
@rhymelph hello, do you still encounter the error?

**Comment by rhymelph** [comment]
@SunZhiC  Thank you!This issues has been solved
