### ISSUE TITLE
[Particle Connect] can not connect the metaMask wallet

### ISSUE THREAD

**Issue by rhymelph** [Particle-Network/particle-flutter#12]
https://github.com/Particle-Network/particle-flutter/assets/20870368/8ce50727-c7cb-4c98-a46c-5b17bcd099cc

**Comment by rhymelph** [comment]
Is anyone there?

**Comment by xxhong** [comment]
Make sure that the chain initialized in sdk is the same as the chain in Metamask

**Comment by rhymelph** [comment]
@xxhong Thanks for your reply, I'm sure I used the same one and reported the same error.

**Comment by xxhong** [comment]
![image](https://github.com/Particle-Network/particle-flutter/assets/2645876/11528681-4867-4af5-a056-3c98e71dabef)
Metamask only supported one chain
