### ISSUE TITLE
Missing argument for parameter 'redirectUniversalLink' in call when build iOS project

### ISSUE THREAD

**Issue by BlackFlagBin** [Particle-Network/particle-flutter#13]
Hi, I'm using these 3 libs in my flutter project and I found an issue when I run it on iOS.
![image](https://github.com/Particle-Network/particle-flutter/assets/17843145/433fe2fc-8f28-4d1f-99f9-bf8c0575e7d1)
![image](https://github.com/Particle-Network/particle-flutter/assets/17843145/57ddf809-1d86-4461-a278-b4e4d8e5d8e5)

Missing argument for parameter 'redirectUniversalLink' in call

**Comment by SunZhiC** [comment]
This bug has been fix in 1.4.11, please upgrade to 1.4.11
