### ISSUE TITLE
Can we have a wallet widget in Flutter SDK?

### ISSUE THREAD

**Issue by BlackFlagBin** [Particle-Network/particle-flutter#15]
For now we can only navigate to the wallet page.  I want a wallet widget in Flutter SDK so that I can use it in a tabview.
For example: I want to show whole wallet UI in the first tab. Can we support it?
![image](https://github.com/Particle-Network/particle-flutter/assets/17843145/ebd97213-4a92-4ba9-b125-c4959c44dfec)

**Comment by xxhong** [comment]
Not supported
