### ISSUE TITLE
Build error when run wallet flutter sdk 1.4.12 on iOS device.

### ISSUE THREAD

**Issue by BlackFlagBin** [Particle-Network/particle-flutter#16]
Cannot assign value of type 'ParticleNetwork.ChainInfo' to type 'OpenBuyNetwork?'
           /Users/lance/.pub-cache/hosted/pub.dev/particle_wallet-1.4.12/ios/Classes/ParticleWalletPlugin.swift:232:26
           
![image](https://github.com/Particle-Network/particle-flutter/assets/17843145/d76ec8fa-b357-4646-a1ad-43ff14d3c720)

**Comment by SunZhiC** [comment]
Try clean cache, then run `pod install` again, there is no code `OpenBuyNetwork` in ParticleWalletPlugin anymore.

**Comment by BlackFlagBin** [comment]
> Try clean cache, then run `pod install` again, there is no code `OpenBuyNetwork` in ParticleWalletPlugin anymore.

Same issue with version 1.4.12. I tried with 1.4.11 and found it was good.

**Comment by SunZhiC** [comment]
this is 1.4.12, https://pub.dev/packages/particle_wallet/versions/1.4.12.tar.gz 
There is no code OpenBuyNetwork in ParticleWalletPlugin anymore.
