### ISSUE TITLE
使用Particle Auth登录成功后，ios设备提示 Safari 浏览器打不开网页，因为网址无效

### ISSUE THREAD

**Issue by BlackFlagBin** [Particle-Network/particle-flutter#17]
![image](https://github.com/Particle-Network/particle-flutter/assets/17843145/360aab15-7f5e-40fd-a3ad-d9886473c17d)

**Comment by SunZhiC** [comment]
如果你使用的是particle_auth，需要在Xcode配置Scheme, 并且在Appdelegate里添加代码，这是文档 
https://developers.particle.network/reference/auth-flutter

**Comment by SunZhiC** [comment]
你可以考虑使用particle_auth_core，这个是原生登录和签名。particle_auth登录和签名都在web中，需要打开内置web
