### ISSUE TITLE
Unable to build the iOS app after adding particle-aa

### ISSUE THREAD

**Issue by benhk2005** [Particle-Network/particle-flutter#18]
Got the following error after adding particle aa SDK to the Flutter project

```
Swift Compiler Error (Xcode): No such module 'AuthCoreAdapter'
/Users/___/.pub-cache/hosted/pub.dev/particle_auth_core-1.4.13/ios/Classes/ParticleAuthCorePlugin.swift:7:7
```

**Comment by benhk2005** [comment]
This error also on 

https://github.com/Particle-Network/particle-flutter/tree/master/particle-aa

and 

https://github.com/Particle-Network/particle-flutter/tree/master/particle-auth-core 

example projects

**Comment by SunZhiC** [comment]
AuthCore does not support any simulator, try to run with a real iPhone.

**Comment by benhk2005** [comment]
> AuthCore does not support any simulator, try to run with a real iPhone.

Oh, its works on real device, thanks and close the issue
