### ISSUE TITLE
Library 'thresh_sig_wasm' not found

### ISSUE THREAD

**Issue by Toketec** [Particle-Network/particle-flutter#19]
<img width="660" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/44367138/96cdb85f-d0f0-4f88-acb1-b387ac8f9324">

simulator ios 15.4 运行报错。

真机、安卓、安卓模拟器运行正常。

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (2 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

cocoapods 版本：1.15.2

xcode 版本：15.4

<img width="335" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/44367138/6ca96e34-8357-40e8-a71d-bac7ef73f4e8">

<img width="923" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/44367138/07278d1c-89c4-4c00-98af-df7b59fa614c">

**Comment by xxhong** [comment]
iOS does not support simulator
