### ISSUE TITLE
ParticleBase.setChainInfo is not working for custom network 

### ISSUE THREAD

**Issue by mhsnprvr** [Particle-Network/particle-flutter#21]
`
final movementChainForParticle = ChainInfo(
  30732,
  'Movement',
  'evm',
  movementChain.chainIcon!,
  'movement testnet',
   'Testnet' ,
  'https://docs.movementnetwork.xyz',
  ChainInfoNativeCurrency('Movement', 'MOVE', 18),
 'https://mevm.devnet.imola.movementlabs.xyz',
  '',
 'https://explorer.devnet.imola.movementlabs.xyz',
  [ChainInfoFeature('EIP1559')],
);
`
after calling 
`await ParticleBase.setChainInfo(movementChainForParticle);
`
`ParticleBase.getChainId()` returns 1

**Comment by SunZhiC** [comment]
We don't support add custom chain now.

**Comment by SunZhiC** [comment]
> Will it be added soon?

There is no specific time

**Comment by mhsnprvr** [comment]
@SunZhiC how can I request to add a network to the list?

**Comment by SunZhiC** [comment]
> @SunZhiC how can I request to add a network to the list?

Here is current supported chains. https://developers.particle.network/guides/network-coverage#network-coverage.
Contact us through discord or telegram.
