### ISSUE TITLE
IOS build error, No such module 'AuthCoreAdapter'

### ISSUE THREAD

**Issue by mhsnprvr** [Particle-Network/particle-flutter#22]
I have this error while building my IOS app, using version "particle_auth_core: 2.1.10", 

> Launching lib/main.dart on iPhone 16 Pro in debug mode...
> Xcode build done.                                           167.8s
> Failed to build iOS app
> Swift Compiler Error (Xcode): No such module 'AuthCoreAdapter'
> /Users/.pub-cache/hosted/pub.dev/particle_auth_core-2.1.10/ios/Classes/ParticleAuthCorePlugin.swift:7:7
> 
> Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 16 Pro.

here is my pod file:
```
# Uncomment this line to define a global platform for your project
platform :ios, '15.1'
source 'https://cdn.cocoapods.org/'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Add the required Particle pods
  pod 'Thresh', '2.0.3'
  pod 'ParticleMPCCore', '2.0.3'
  pod 'ParticleAuthCore', '2.0.3'
  pod 'AuthCoreAdapter', '2.0.3'
  pod 'ParticleNetworkBase', '2.0.3'
  pod 'ParticleNetworkChains', '2.0.3'
  pod 'ConnectCommon', '2.0.3'

  # Additional dependencies
  pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
  pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  
  # Add BUILD_LIBRARY_FOR_DISTRIBUTION setting
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end

  # Disable code signing for resource bundles
  installer.target_installation_results.pod_target_installation_results
    .each do |pod_name, target_installation_result|
    target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
      resource_bundle_target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  
  # Set minimum iOS version for all targets
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end
end
```

**Comment by SunZhiC** [comment]
> I have this error while building my IOS app, using version "particle_auth_core: 2.1.10",
> 
> > Launching lib/main.dart on iPhone 16 Pro in debug mode...
> > Xcode build done.                                           167.8s
> > Failed to build iOS app
> > Swift Compiler Error (Xcode): No such module 'AuthCoreAdapter'
> > /Users/.pub-cache/hosted/pub.dev/particle_auth_core-2.1.10/ios/Classes/ParticleAuthCorePlugin.swift:7:7
> > Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
> > Could not build the application for the simulator.
> > Error launching application on iPhone 16 Pro.
> 
> here is my pod file:
> 
> ```
> # Uncomment this line to define a global platform for your project
> platform :ios, '15.1'
> source 'https://cdn.cocoapods.org/'
> 
> # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> 
> project 'Runner', {
>   'Debug' => :debug,
>   'Profile' => :release,
>   'Release' => :release,
> }
> 
> def flutter_root
>   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
>   unless File.exist?(generated_xcode_build_settings_path)
>     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
>   end
> 
>   File.foreach(generated_xcode_build_settings_path) do |line|
>     matches = line.match(/FLUTTER_ROOT\=(.*)/)
>     return matches[1].strip if matches
>   end
>   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
> end
> 
> require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
> 
> flutter_ios_podfile_setup
> 
> target 'Runner' do
>   use_frameworks! :linkage => :static
>   use_modular_headers!
> 
>   # Add the required Particle pods
>   pod 'Thresh', '2.0.3'
>   pod 'ParticleMPCCore', '2.0.3'
>   pod 'ParticleAuthCore', '2.0.3'
>   pod 'AuthCoreAdapter', '2.0.3'
>   pod 'ParticleNetworkBase', '2.0.3'
>   pod 'ParticleNetworkChains', '2.0.3'
>   pod 'ConnectCommon', '2.0.3'
> 
>   # Additional dependencies
>   pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
>   pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'
> 
>   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
>   target 'RunnerTests' do
>     inherit! :search_paths
>   end
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>   end
>   
>   # Add BUILD_LIBRARY_FOR_DISTRIBUTION setting
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
>     end
>   end
> 
>   # Disable code signing for resource bundles
>   installer.target_installation_results.pod_target_installation_results
>     .each do |pod_name, target_installation_result|
>     target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
>       resource_bundle_target.build_configurations.each do |config|
>         config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>       end
>     end
>   end
>   
>   # Set minimum iOS version for all targets
>   installer.generated_projects.each do |project|
>     project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
>       end
>     end
>   end
> end
> ```

Don't support any simulators, try use a real iPhone.

**Comment by mhsnprvr** [comment]
> > I have this error while building my IOS app, using version "particle_auth_core: 2.1.10",
> > > Launching lib/main.dart on iPhone 16 Pro in debug mode...
> > > Xcode build done.                                           167.8s
> > > Failed to build iOS app
> > > Swift Compiler Error (Xcode): No such module 'AuthCoreAdapter'
> > > /Users/.pub-cache/hosted/pub.dev/particle_auth_core-2.1.10/ios/Classes/ParticleAuthCorePlugin.swift:7:7
> > > Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
> > > Could not build the application for the simulator.
> > > Error launching application on iPhone 16 Pro.
> > 
> > 
> > here is my pod file:
> > ```
> > # Uncomment this line to define a global platform for your project
> > platform :ios, '15.1'
> > source 'https://cdn.cocoapods.org/'
> > 
> > # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> > ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> > 
> > project 'Runner', {
> >   'Debug' => :debug,
> >   'Profile' => :release,
> >   'Release' => :release,
> > }
> > 
> > def flutter_root
> >   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
> >   unless File.exist?(generated_xcode_build_settings_path)
> >     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
> >   end
> > 
> >   File.foreach(generated_xcode_build_settings_path) do |line|
> >     matches = line.match(/FLUTTER_ROOT\=(.*)/)
> >     return matches[1].strip if matches
> >   end
> >   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
> > end
> > 
> > require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
> > 
> > flutter_ios_podfile_setup
> > 
> > target 'Runner' do
> >   use_frameworks! :linkage => :static
> >   use_modular_headers!
> > 
> >   # Add the required Particle pods
> >   pod 'Thresh', '2.0.3'
> >   pod 'ParticleMPCCore', '2.0.3'
> >   pod 'ParticleAuthCore', '2.0.3'
> >   pod 'AuthCoreAdapter', '2.0.3'
> >   pod 'ParticleNetworkBase', '2.0.3'
> >   pod 'ParticleNetworkChains', '2.0.3'
> >   pod 'ConnectCommon', '2.0.3'
> > 
> >   # Additional dependencies
> >   pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
> >   pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'
> > 
> >   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
> >   target 'RunnerTests' do
> >     inherit! :search_paths
> >   end
> > end
> > 
> > post_install do |installer|
> >   installer.pods_project.targets.each do |target|
> >     flutter_additional_ios_build_settings(target)
> >   end
> >   
> >   # Add BUILD_LIBRARY_FOR_DISTRIBUTION setting
> >   installer.pods_project.targets.each do |target|
> >     target.build_configurations.each do |config|
> >       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
> >     end
> >   end
> > 
> >   # Disable code signing for resource bundles
> >   installer.target_installation_results.pod_target_installation_results
> >     .each do |pod_name, target_installation_result|
> >     target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
> >       resource_bundle_target.build_configurations.each do |config|
> >         config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
> >       end
> >     end
> >   end
> >   
> >   # Set minimum iOS version for all targets
> >   installer.generated_projects.each do |project|
> >     project.targets.each do |target|
> >       target.build_configurations.each do |config|
> >         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
> >       end
> >     end
> >   end
> > end
> > ```
> 
> Don't support any simulators, try use a real iPhone.
