### ISSUE TITLE
No such module 'ParticleNetworkBase'

### ISSUE THREAD

**Issue by Toketec** [Particle-Network/particle-flutter#3]
按照文档配置了项目，ios端提示No such module 'ParticleNetworkBase'
下载了demo直接运行auth的example依然提示No such module 'ParticleNetworkBase'
<img width="1029" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/44367138/50912d59-00ac-4b7d-ade0-1bbcc7977f42">

**Comment by SunZhiC** [comment]
1. 是否配置了Podfile 需要添加一个声明 https://docs.particle.network/developers/auth-service/sdks/flutter 中3.8. 
```
post_install do |installer|
installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
  config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
 end
```
2. 目前不支持x86_64（inter）模拟器，你使用真机或者arm64(M1 or M2)试试

**Comment by Toketec** [comment]
我的pod内容如下：
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
end


并且使用的是M2max芯片的mac电脑

**Comment by SunZhiC** [comment]
你可以注释这行吗？
# use_modular_headers!

**Comment by Toketec** [comment]
已经注释了，依然是这样❤️。。

**Comment by SunZhiC** [comment]
1.你有删除Podfile.lock ，Pods文件夹和Xcode缓存吗？ 然后重新执行的pod install 吗

**Comment by Toketec** [comment]
感谢，我来试一下，稍后回复情况❤️

**Comment by Toketec** [comment]
@SunZhiC 清理了所有缓存，cocoa、pub、xcode，并使用本项目直接运行，依然包相同的错误，请问是否对flutter版本有要求？

**Comment by Toketec** [comment]
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (4 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

**Comment by SunZhiC** [comment]
你可以上传一个仓库，我实际看看吗，我觉得对flutter版本应该没要求

**Comment by Toketec** [comment]
我使用的就是本仓库的代码，请问贵公司目前使用的开发环境版本是多少，我来试一下，感谢

**Comment by SunZhiC** [comment]
我开发的时候，使用的就是这个example, 开发环境应该在https://github.com/Particle-Network/particle-flutter/blob/master/particle-auth/example/pubspec.yaml 这个文件里面了。
你可以试试直接使用Xcode打开iOS项目试试吗，Xcode要求是 >= 14.1。
如果你可以自建一个仓库，上传你无法运行的demo，我们可以直接看。

**Comment by Toketec** [comment]
@SunZhiC flutter的开发环境是多少呀，我也复刻一下，试了一天差点放弃了。。。🙏🏻

**Comment by SunZhiC** [comment]
Flutter 3.4.0-34.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 71520442d4 (10 months ago) • 2022-10-05 16:38:28 -0500
Engine • revision db0cbb2145
Tools • Dart 2.19.0 (build 2.19.0-255.2.beta) • DevTools 2.18.0

**Comment by SunZhiC** [comment]
> @SunZhiC 清理了所有缓存，cocoa、pub、xcode，并使用本项目直接运行，依然包相同的错误，请问是否对flutter版本有要求？ ParticleAuthService 版本号1.0.1和1.0.2都试过了，都是一样的错误，并且把本项目的依赖从上级项目依赖换成particle_auth: ^1.0.4后依然报错 <img alt="image" width="619" src="https://user-images.githubusercontent.com/44367138/259925283-1dce336c-8cbe-4e3a-83a1-5b5393ef3f60.png"> 指向的问题是 <img alt="image" width="632" src="https://user-images.githubusercontent.com/44367138/259925449-025b8a16-4d8b-4d37-86a0-a367150399e9.png"> 这个不存在

你的报错，我认为不是flutter的原因，是Xcode cocoapods等配置的原因，应该是执行pod install 后项目没有正确的配置导致的。你可以打开Xcode查看你项目中Pods列表下的各个子依赖的包是不是这样的。
![image](https://github.com/Particle-Network/particle-flutter/assets/18244874/25484930-f8f0-44ed-aa4e-99e3776a19a8)
图标是否是黄色公文包💼和红色靶子🎯。

**Comment by Toketec** [comment]
1、因为最新版的代码在安装pod时报错
<img width="819" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/44367138/b663eeb9-e53d-49ca-97a8-d88222798272">
所以我先删除了  ∫  字符进行pod install 
安装结果如下：
<img width="1086" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/44367138/74b97412-7688-4888-8482-2bae401ffcf8">
<img width="1131" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/44367138/03cc1c15-ec0f-40e8-beb2-c9854e1e7a8b">
2、紧接着我就打卡main.dart运行debug，使用的是iPhone14pro（arm）模拟器
得到了报错：
<img width="1118" alt="image" src="https://github.com/Particle-Network/particle-flutter/assets/44367138/88a0113b-0729-4ac2-8c3b-1bd7bee4b95f">

**Comment by SunZhiC** [comment]
好的，我现在升级到最新的flutter版本试一下。

**Comment by Toketec** [comment]
@SunZhiC 对了我的cocoapod版本是1.12.1

**Comment by Toketec** [comment]
@SunZhiC 
可以吗？不可以的话准备含泪换一家了。。

**Comment by SunZhiC** [comment]
升级之后测试，使用真机可以，使用模拟器也遇到报错，正在排查模拟器的原因，你可以先使用真机开发。

**Comment by SunZhiC** [comment]
> Flutter 3.4.0-34.1.pre • channel beta • https://github.com/flutter/flutter.git Framework • revision 71520442d4 (10 months ago) • 2022-10-05 16:38:28 -0500 Engine • revision db0cbb2145 Tools • Dart 2.19.0 (build 2.19.0-255.2.beta) • DevTools 2.18.0

回退到这个flutter版本测试模拟器是可行的。
你可以暂时回退到这个版本使用模拟器测试，或者版本不变直接使用真机测试。

cd 到你flutter目录
```
git checkout 3.4.0-34.1.pre
```

之后，我再研究下如何在3.10.6上模拟器运行，目前没找到原因。

**Comment by Toketec** [comment]
好的，这个3.4版本的似乎是一个特殊版本，在官网已经没有下载地址，只有3.3、3.7、3.10，不过这三个版本都试过了，都是报一样的缺依赖问题。

**Comment by SunZhiC** [comment]
![image](https://github.com/Particle-Network/particle-flutter/assets/18244874/1a251797-87b0-4faf-98d0-0c2276f0d7d5)
这个地方设置成arm64， 然后清空Pods文件夹和Podfile.lock 重新跑一下就好了，模拟器可以运行了。
使用如下版本

Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (5 days ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0

**Comment by varunlohade** [comment]
@SunZhiC I am getting the same issue and I did all the steps you have mentioned 


Podfile
`
platform :ios, '14.0'


ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  pod 'ParticleNetworkBase', '1.0.6'
  pod 'ParticleAuthService', '1.0.6'
  pod 'ParticleBiconomy', '1.0.6'

  pod 'ParticleConnect', '0.2.9'
  pod 'ConnectWalletConnectAdapter', '0.2.9'
  pod 'ConnectSolanaAdapter', '0.2.9'
  pod 'ConnectEVMAdapter', '0.2.9'
  pod 'ConnectCommon', '0.2.9'
  pod 'ConnectPhantomAdapter', '0.2.9'
  



  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
`

**Comment by SunZhiC** [comment]
@varunlohade our SDK doesn't support x86_64 simulator, did you run with a real iPhone or macbook M1/M2 ?
Did you set Architectures to `arm64` then remove all xcode caches, Pods and Podfile.lock, rerun `pod install` ?

**Comment by varunlohade** [comment]
Hey @SunZhiC  I have tried this but now i am facing
this issue
I am running on iPhone 14
<img width="1084" alt="Screenshot 2023-10-09 at 5 10 24 PM" src="https://github.com/Particle-Network/particle-flutter/assets/50517140/2d04390a-26c5-405f-b623-1d6278d5cec1">

**Comment by SunZhiC** [comment]
> Hey @SunZhiC  I have tried this but now i am facing
> 
> this issue
> 
> I am running on iPhone 14
> 
> 
> 
> 
> 
> 
> 
> <img width="1084" alt="Screenshot 2023-10-09 at 5 10 24 PM" src="https://github.com/Particle-Network/particle-flutter/assets/50517140/2d04390a-26c5-405f-b623-1d6278d5cec1">
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  pod 'ParticleNetworkBase', '1.0.6'
> 
>   pod 'ParticleAuthService', '1.0.6'
> 
>   pod 'ParticleBiconomy', '1.0.6'
> 
>   pod 'ParticleConnect', '0.2.9'
> 
>   pod 'ConnectWalletConnectAdapter', '0.2.9'
> 
>   pod 'ConnectEVMAdapter', '0.2.9'
> 
>   pod 'ConnectCommon', '0.2.9'
> 
>   
> 
> 

Hi, what is your Xcode version number?

**Comment by varunlohade** [comment]
Hi, I am on Xcode 14.3
I have tried running the project for Swift toolchain 5.3, 5.5.3 and 5.7 as well.
I fixed most of the issues but now I am getting this error, not sure how to fix this.

<img width="446" alt="Screenshot 2023-10-11 at 4 05 52 PM" src="https://github.com/Particle-Network/particle-flutter/assets/50517140/857fd754-5d2e-4265-b75d-74ed87bb576e">



I tried running particle-connect/example but I am getting this error
<img width="598" alt="Screenshot 2023-10-11 at 5 06 04 PM" src="https://github.com/Particle-Network/particle-flutter/assets/50517140/b06c5228-c993-43ba-a095-89a8149f8318">

**Comment by SunZhiC** [comment]
> Hey the errors for logging library and swift-log are now gone, I am on Swift version 5.7.2
> 
> <img alt="Screenshot 2023-10-11 at 9 10 15 PM" width="598" src="https://user-images.githubusercontent.com/50517140/274336161-699e92b7-4564-4976-a528-e464e1c979f1.png">
> but I found this issue now.

1. The secp256k1 is not our sub modules, you can explore Podfile.lock, find out which module dependents secp256k1.

**Comment by lpylpyleo** [comment]
> 升级之后测试，使用真机可以，使用模拟器也遇到报错，正在排查模拟器的原因，你可以先使用真机开发。

问题依然存在，最新版flutter，XCode, particle SDK

**Comment by SunZhiC** [comment]
> ![image](https://user-images.githubusercontent.com/18244874/261953552-1a251797-87b0-4faf-98d0-0c2276f0d7d5.png) 这个地方设置成arm64， 然后清空Pods文件夹和Podfile.lock 重新跑一下就好了，模拟器可以运行了。 使用如下版本
> 
> Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git Framework • revision efbf63d9c6 (5 days ago) • 2023-08-15 21:05:06 -0500 Engine • revision 1ac611c64e Tools • Dart 3.1.0 • DevTools 2.25.0

@lpylpyleo  使用这个方法试一下，这个是可以解决模拟器运行的，仅限M1/M2的mac机型，不支持x86_64 芯片。
