### ISSUE TITLE
`particle_wallet` running failed in debug mode.

### ISSUE THREAD

**Issue by Ce1ling** [Particle-Network/particle-flutter#6]
你好，当我在 `pubspec.yaml` 安装了 `particle_wallet` 后，运行程序，就会得到这个错误：

```debug console
/xxx/android/app/src/debug/AndroidManifest.xml:13:18-66 Error:
	Attribute application@fullBackupContent value=(@xml/pn_backup_rules) from [network.particle:auth-core:1.0.1] AndroidManifest.xml:13:18-66
	is also present at [com.walletconnect:sign:2.15.0] AndroidManifest.xml:9:9-54 value=(@xml/backup_rules).
	Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:19:5-80:19 to override.
```

但是安装 `particle_connect` 或 `particle_auth` 不会出现词错误。

我按照错误提示，我配置了 `AndroidManifest.xml` 的 `<application>`，就会得到：

```debug console
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing /xxx/android/app/src/main/AndroidManifest.xml
```

我确定我按照(官方文档)[https://docs.particle.network/developers/wallet-service/sdks/flutter]配置好了安卓环境。

当我在 `pubspec.yaml` 注释掉 `particle_wallet` 包后，我的程序就可以正常运行。

能否帮助我？非常感谢！

**Comment by xxhong** [comment]
[参考这个文件的第10行](https://github.com/Particle-Network/particle-flutter/blob/master/particle-wallet/example/android/app/src/main/AndroidManifest.xml)

**Comment by Ce1ling** [comment]
> [参考这个文件的第10行](https://github.com/Particle-Network/particle-flutter/blob/master/particle-wallet/example/android/app/src/main/AndroidManifest.xml)


Thanks, but I had configured this at the time, and it still didn’t work.

However, I’ve already identified the issue, which is configuring both line 7 and line 10 of this file, like this:

```xml
<application
        android:fullBackupContent="@xml/pn_backup_rules"
        tools:replace="android:fullBackupContent">
        <!-- other config -->
</application>
```
