### ISSUE TITLE
Can Flutter Web be supported?

### ISSUE THREAD

**Issue by Wing-Li** [Particle-Network/particle-flutter#8]
Currently, Flutter only supports Android and iOS, and does not support the Web. However, I see that the types of pure web SDK support are very comprehensive. Can Flutter's support be added?
Flutter's support for the Web has been increasing, and I believe the demand for Flutter Web will also continue to grow. I am in urgent need of Flutter Web support.

**Comment by SunZhiC** [comment]
We currently have no plans for a Flutter web SDK.
